export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	SET_PRODUCT_DATA: 'SET_PRODUCT_DATA',
	CLOSE_MODAL: 'CLOSE_MODAL',
	OPEN_MODAL: 'OPEN_MODAL',
	RESET_PRODUCT_DATA: 'RESET_PRODUCT_DATA',
	SET_CATEGORIES: 'SET_CATEGORIES',
	ADD_TO_ORDER: 'ADD_TO_ORDER',
	CLEAR_CART: 'CLEAR_CART',
	REMOVE_FROM_CART: 'REMOVE_FROM_CART',
	SET_ORDER_DATA: 'SET_ORDER_DATA',
	ADD_TO_CART: 'ADD_TO_CART',
};
